AWSTemplateFormatVersion: "2010-09-09"
Description: CyberInsight YouTube Test VPC in us-east-1
Resources:
  NwktVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      InstanceTenancy: default
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: YouTube-VPC-01